trigger:
  branches:
    include:
    - main
    - master
    - ia-site
    - refs/tags/v*
    - refs/heads/review/*
    - refs/heads/dev/*
    - refs/heads/user/*
  paths:
    exclude:
    - CHANGELOG.md
    - README.md

pool:
  vmImage: 'ubuntu-latest'

steps:

  - script: npm ci
    displayName: 'Install'

  - task: SonarQubePrepare@5
    displayName: 'Prepare analysis on SonarQube'
    inputs:
      SonarQube: 'nhsuk-service-manual'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'service-manual'
      extraProperties: |
        sonar.javascript.lcov.reportPaths=coverage/lcov.info
        sonar.coverage.exclusions=**/*.config.js,**/coverage/**

  - script: npm run build
    displayName: 'Build'

  - script: npm run test
    displayName: 'Test'
  
  - task: SonarQubeAnalyze@5
    displayName: 'Run code analysis' 

  - task: SonarQubePublish@5
    displayName: 'Publish quality gate result'
    inputs:
      pollingTimeoutSec: '300'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
    displayName: 'Create file archive to publish'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish files to Azure Pipelines'
